"""Explicit Isaac Lab configuration for the 23-DOF PND Adam SP robot."""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg
from pxr import Sdf, Usd, UsdPhysics

from instinctlab.sim.robot_spec import BackendAsset, JointProperties, RobotSpec

RESOURCE_ROOT = Path(__file__).resolve().parent.parent / "resources" / "adam_sp"
ADAM_SP_23DOF_URDF = RESOURCE_ROOT / "urdf" / "adam_sp_23_dof.urdf"
ADAM_SP_23DOF_XML = RESOURCE_ROOT / "xml" / "adam_sp_23_dof.xml"

ADAM_SP_23DOF_JOINT_NAMES = (
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
    "waist_roll_joint",
    "waist_pitch_joint",
    "waist_yaw_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
)

ADAM_SP_23DOF_BODY_NAMES = (
    "pelvis",
    "left_hip_pitch_link",
    "left_hip_roll_link",
    "left_hip_yaw_link",
    "left_knee_link",
    "left_ankle_pitch_link",
    "left_ankle_roll_link",
    "right_hip_pitch_link",
    "right_hip_roll_link",
    "right_hip_yaw_link",
    "right_knee_link",
    "right_ankle_pitch_link",
    "right_ankle_roll_link",
    "waist_roll_link",
    "waist_pitch_link",
    "torso_link",
    "left_shoulder_pitch_link",
    "left_shoulder_roll_link",
    "left_shoulder_yaw_link",
    "left_elbow_link",
    "left_wrist_yaw_link",
    "left_wrist_pitch_link",
    "left_wrist_roll_link",
    "L_thumb_proximal_base",
    "L_thumb_proximal",
    "L_thumb_intermediate",
    "L_thumb_distal",
    "L_index_proximal",
    "L_index_distal",
    "L_middle_proximal",
    "L_middle_distal",
    "L_ring_proximal",
    "L_ring_distal",
    "L_pinky_proximal",
    "L_pinky_distal",
    "right_shoulder_pitch_link",
    "right_shoulder_roll_link",
    "right_shoulder_yaw_link",
    "right_elbow_link",
    "right_wrist_yaw_link",
    "right_wrist_pitch_link",
    "right_wrist_roll_link",
    "R_thumb_proximal_base",
    "R_thumb_proximal",
    "R_thumb_intermediate",
    "R_thumb_distal",
    "R_index_proximal",
    "R_index_distal",
    "R_middle_proximal",
    "R_middle_distal",
    "R_ring_proximal",
    "R_ring_distal",
    "R_pinky_proximal",
    "R_pinky_distal",
    "imu_link",
)

ADAM_SP_23DOF_COLLISION_BODY_NAMES = (
    "pelvis",
    "left_hip_roll_link",
    "left_hip_yaw_link",
    "left_knee_link",
    "left_ankle_roll_link",
    "right_hip_roll_link",
    "right_hip_yaw_link",
    "right_knee_link",
    "right_ankle_roll_link",
    "torso_link",
    "left_shoulder_yaw_link",
    "left_elbow_link",
    "left_wrist_roll_link",
    "right_shoulder_yaw_link",
    "right_elbow_link",
    "right_wrist_roll_link",
)

ADAM_SP_23DOF_JOINT_PROPERTIES = (
    JointProperties(
        name="left_hip_pitch_joint",
        default_pos=-0.32,
        stiffness=300.0,
        damping=7.0,
        armature=0.13426,
        effort_limit=230.0,
        velocity_limit=15.0,
        action_scale=0.19166666666666668,
        actuator_group="legs",
    ),
    JointProperties(
        name="left_hip_roll_joint",
        default_pos=0.0,
        stiffness=600.0,
        damping=10.0,
        armature=0.281573,
        effort_limit=180.0,
        velocity_limit=8.0,
        action_scale=0.075,
        actuator_group="legs",
    ),
    JointProperties(
        name="left_hip_yaw_joint",
        default_pos=-0.18,
        stiffness=300.0,
        damping=2.0,
        armature=0.23409,
        effort_limit=105.0,
        velocity_limit=8.0,
        action_scale=0.0875,
        actuator_group="legs",
    ),
    JointProperties(
        name="left_knee_joint",
        default_pos=0.66,
        stiffness=300.0,
        damping=7.0,
        armature=0.13426,
        effort_limit=230.0,
        velocity_limit=15.0,
        action_scale=0.19166666666666668,
        actuator_group="legs",
    ),
    JointProperties(
        name="left_ankle_pitch_joint",
        default_pos=-0.39,
        stiffness=130.0,
        damping=3.5,
        armature=0.0549,
        effort_limit=80.0,
        velocity_limit=20.0,
        action_scale=0.15384615384615385,
        actuator_group="feet",
    ),
    JointProperties(
        name="left_ankle_roll_joint",
        default_pos=0.0,
        stiffness=70.0,
        damping=2.0,
        armature=0.0549,
        effort_limit=40.0,
        velocity_limit=20.0,
        action_scale=0.14285714285714285,
        actuator_group="feet",
    ),
    JointProperties(
        name="right_hip_pitch_joint",
        default_pos=-0.32,
        stiffness=300.0,
        damping=7.0,
        armature=0.13426,
        effort_limit=230.0,
        velocity_limit=15.0,
        action_scale=0.19166666666666668,
        actuator_group="legs",
    ),
    JointProperties(
        name="right_hip_roll_joint",
        default_pos=0.0,
        stiffness=600.0,
        damping=10.0,
        armature=0.281573,
        effort_limit=180.0,
        velocity_limit=8.0,
        action_scale=0.075,
        actuator_group="legs",
    ),
    JointProperties(
        name="right_hip_yaw_joint",
        default_pos=0.18,
        stiffness=300.0,
        damping=2.0,
        armature=0.23409,
        effort_limit=105.0,
        velocity_limit=8.0,
        action_scale=0.0875,
        actuator_group="legs",
    ),
    JointProperties(
        name="right_knee_joint",
        default_pos=0.66,
        stiffness=300.0,
        damping=7.0,
        armature=0.13426,
        effort_limit=230.0,
        velocity_limit=15.0,
        action_scale=0.19166666666666668,
        actuator_group="legs",
    ),
    JointProperties(
        name="right_ankle_pitch_joint",
        default_pos=-0.39,
        stiffness=130.0,
        damping=3.5,
        armature=0.0549,
        effort_limit=80.0,
        velocity_limit=20.0,
        action_scale=0.15384615384615385,
        actuator_group="feet",
    ),
    JointProperties(
        name="right_ankle_roll_joint",
        default_pos=0.0,
        stiffness=70.0,
        damping=2.0,
        armature=0.0549,
        effort_limit=40.0,
        velocity_limit=20.0,
        action_scale=0.14285714285714285,
        actuator_group="feet",
    ),
    JointProperties(
        name="waist_roll_joint",
        default_pos=0.0,
        stiffness=400.0,
        damping=11.0,
        armature=0.23409,
        effort_limit=150.0,
        velocity_limit=8.0,
        action_scale=0.09375,
        actuator_group="waist",
    ),
    JointProperties(
        name="waist_pitch_joint",
        default_pos=0.0,
        stiffness=400.0,
        damping=11.0,
        armature=0.23409,
        effort_limit=150.0,
        velocity_limit=8.0,
        action_scale=0.09375,
        actuator_group="waist",
    ),
    JointProperties(
        name="waist_yaw_joint",
        default_pos=0.0,
        stiffness=400.0,
        damping=11.0,
        armature=0.23409,
        effort_limit=150.0,
        velocity_limit=8.0,
        action_scale=0.09375,
        actuator_group="waist",
    ),
    JointProperties(
        name="left_shoulder_pitch_joint",
        default_pos=0.0,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=65.0,
        velocity_limit=8.0,
        action_scale=0.2708333333333333,
        actuator_group="arms",
    ),
    JointProperties(
        name="left_shoulder_roll_joint",
        default_pos=0.1,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=65.0,
        velocity_limit=8.0,
        action_scale=0.2708333333333333,
        actuator_group="arms",
    ),
    JointProperties(
        name="left_shoulder_yaw_joint",
        default_pos=0.0,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=65.0,
        velocity_limit=8.0,
        action_scale=0.2708333333333333,
        actuator_group="arms",
    ),
    JointProperties(
        name="left_elbow_joint",
        default_pos=-0.3,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=30.0,
        velocity_limit=8.0,
        action_scale=0.125,
        actuator_group="arms",
    ),
    JointProperties(
        name="right_shoulder_pitch_joint",
        default_pos=0.0,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=65.0,
        velocity_limit=8.0,
        action_scale=0.2708333333333333,
        actuator_group="arms",
    ),
    JointProperties(
        name="right_shoulder_roll_joint",
        default_pos=-0.1,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=65.0,
        velocity_limit=8.0,
        action_scale=0.2708333333333333,
        actuator_group="arms",
    ),
    JointProperties(
        name="right_shoulder_yaw_joint",
        default_pos=0.0,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=65.0,
        velocity_limit=8.0,
        action_scale=0.2708333333333333,
        actuator_group="arms",
    ),
    JointProperties(
        name="right_elbow_joint",
        default_pos=-0.3,
        stiffness=60.0,
        damping=3.0,
        armature=0.01,
        effort_limit=30.0,
        velocity_limit=8.0,
        action_scale=0.125,
        actuator_group="arms",
    ),
)

ADAM_SP_23DOF_ROBOT = RobotSpec(
    name="adam_sp_23dof",
    schema_version="dfs_v1",
    asset_id="adam_sp_23dof",
    root_body="pelvis",
    joint_names=ADAM_SP_23DOF_JOINT_NAMES,
    body_names=ADAM_SP_23DOF_BODY_NAMES,
    frame_names=("imu_link",),
    collision_body_names=ADAM_SP_23DOF_COLLISION_BODY_NAMES,
    joint_properties=ADAM_SP_23DOF_JOINT_PROPERTIES,
    assets=(
        BackendAsset(
            backend="isaacsim",
            path=str(ADAM_SP_23DOF_URDF),
            import_options={
                "prim_path": "{ENV_REGEX_NS}/Robot",
                "fix_base": False,
                "merge_fixed_joints": False,
                "replace_cylinders_with_capsules": False,
            },
        ),
        BackendAsset(backend="mjlab", path=str(ADAM_SP_23DOF_XML)),
    ),
    default_root_pos=(0.0, 0.0, 0.89),
    default_root_quat_wxyz=(1.0, 0.0, 0.0, 0.0),
    soft_joint_pos_limit_factor=0.9,
    actuator_delay=(0, 0),
)

ADAM_SP_23DOF_ROBOT.validate()


@sim_utils.clone
def spawn_adam_sp_23dof(
    prim_path: str,
    cfg: sim_utils.UrdfFileCfg,
    translation: tuple[float, float, float] | None = None,
    orientation: tuple[float, float, float, float] | None = None,
    **kwargs,
) -> Usd.Prim:
    """Spawn Adam SP and suppress the fixed-chain forearm/hand overlaps."""
    # This function owns cloning so the authored relationships are copied to every environment.
    # Call Isaac Lab's undecorated URDF importer here; calling its public wrapper would clone first.
    robot = sim_utils.spawn_from_urdf.__wrapped__(
        prim_path,
        cfg,
        translation,
        orientation,
        **kwargs,
    )
    stage = robot.GetStage()

    left_elbow = stage.GetPrimAtPath(f"{prim_path}/left_elbow_link")
    left_elbow_filtered_pairs = UsdPhysics.FilteredPairsAPI.Apply(left_elbow).CreateFilteredPairsRel()
    left_elbow_filtered_pairs.AddTarget(Sdf.Path(f"{prim_path}/left_wrist_roll_link"))

    right_elbow = stage.GetPrimAtPath(f"{prim_path}/right_elbow_link")
    right_elbow_filtered_pairs = UsdPhysics.FilteredPairsAPI.Apply(right_elbow).CreateFilteredPairsRel()
    right_elbow_filtered_pairs.AddTarget(Sdf.Path(f"{prim_path}/right_wrist_roll_link"))

    return robot

ADAM_SP_23DOF_ACTUATORS = {
    "hip_pitch_knee": ImplicitActuatorCfg(
        joint_names_expr=[
            "left_hip_pitch_joint",
            "left_knee_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
        ],
        stiffness=300.0,
        damping=7.0,
        effort_limit_sim=230.0,
        velocity_limit_sim=15.0,
        armature=0.13426,
    ),
    "hip_roll": ImplicitActuatorCfg(
        joint_names_expr=["left_hip_roll_joint", "right_hip_roll_joint"],
        stiffness=600.0,
        damping=10.0,
        effort_limit_sim=180.0,
        velocity_limit_sim=8.0,
        armature=0.281573,
    ),
    "hip_yaw": ImplicitActuatorCfg(
        joint_names_expr=["left_hip_yaw_joint", "right_hip_yaw_joint"],
        stiffness=300.0,
        damping=2.0,
        effort_limit_sim=105.0,
        velocity_limit_sim=8.0,
        armature=0.23409,
    ),
    "ankle_pitch": ImplicitActuatorCfg(
        joint_names_expr=["left_ankle_pitch_joint", "right_ankle_pitch_joint"],
        stiffness=130.0,
        damping=3.5,
        effort_limit_sim=80.0,
        velocity_limit_sim=20.0,
        armature=0.0549,
    ),
    "ankle_roll": ImplicitActuatorCfg(
        joint_names_expr=["left_ankle_roll_joint", "right_ankle_roll_joint"],
        stiffness=70.0,
        damping=2.0,
        effort_limit_sim=40.0,
        velocity_limit_sim=20.0,
        armature=0.0549,
    ),
    "waist": ImplicitActuatorCfg(
        joint_names_expr=[
            "waist_roll_joint",
            "waist_pitch_joint",
            "waist_yaw_joint",
        ],
        stiffness=400.0,
        damping=11.0,
        effort_limit_sim=150.0,
        velocity_limit_sim=8.0,
        armature=0.23409,
    ),
    "shoulder": ImplicitActuatorCfg(
        joint_names_expr=[
            "left_shoulder_pitch_joint",
            "left_shoulder_roll_joint",
            "left_shoulder_yaw_joint",
            "right_shoulder_pitch_joint",
            "right_shoulder_roll_joint",
            "right_shoulder_yaw_joint",
        ],
        stiffness=60.0,
        damping=3.0,
        effort_limit_sim=65.0,
        velocity_limit_sim=8.0,
        armature=0.01,
    ),
    "elbow": ImplicitActuatorCfg(
        joint_names_expr=["left_elbow_joint", "right_elbow_joint"],
        stiffness=60.0,
        damping=3.0,
        effort_limit_sim=30.0,
        velocity_limit_sim=8.0,
        armature=0.01,
    ),
}

ADAM_SP_23DOF_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        func=spawn_adam_sp_23dof,
        asset_path=str(ADAM_SP_23DOF_URDF),
        fix_base=False,
        merge_fixed_joints=False,
        replace_cylinders_with_capsules=False,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(
                stiffness=0.0,
                damping=0.0,
            )
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.89),
        joint_pos={
            "left_hip_pitch_joint": -0.32,
            "left_hip_roll_joint": 0.0,
            "left_hip_yaw_joint": -0.18,
            "left_knee_joint": 0.66,
            "left_ankle_pitch_joint": -0.39,
            "left_ankle_roll_joint": 0.0,
            "right_hip_pitch_joint": -0.32,
            "right_hip_roll_joint": 0.0,
            "right_hip_yaw_joint": 0.18,
            "right_knee_joint": 0.66,
            "right_ankle_pitch_joint": -0.39,
            "right_ankle_roll_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_pitch_joint": 0.0,
            "waist_yaw_joint": 0.0,
            "left_shoulder_pitch_joint": 0.0,
            "left_shoulder_roll_joint": 0.1,
            "left_shoulder_yaw_joint": 0.0,
            "left_elbow_joint": -0.3,
            "right_shoulder_pitch_joint": 0.0,
            "right_shoulder_roll_joint": -0.1,
            "right_shoulder_yaw_joint": 0.0,
            "right_elbow_joint": -0.3,
        },
        joint_vel={
            "left_hip_pitch_joint": 0.0,
            "left_hip_roll_joint": 0.0,
            "left_hip_yaw_joint": 0.0,
            "left_knee_joint": 0.0,
            "left_ankle_pitch_joint": 0.0,
            "left_ankle_roll_joint": 0.0,
            "right_hip_pitch_joint": 0.0,
            "right_hip_roll_joint": 0.0,
            "right_hip_yaw_joint": 0.0,
            "right_knee_joint": 0.0,
            "right_ankle_pitch_joint": 0.0,
            "right_ankle_roll_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_pitch_joint": 0.0,
            "waist_yaw_joint": 0.0,
            "left_shoulder_pitch_joint": 0.0,
            "left_shoulder_roll_joint": 0.0,
            "left_shoulder_yaw_joint": 0.0,
            "left_elbow_joint": 0.0,
            "right_shoulder_pitch_joint": 0.0,
            "right_shoulder_roll_joint": 0.0,
            "right_shoulder_yaw_joint": 0.0,
            "right_elbow_joint": 0.0,
        },
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators=ADAM_SP_23DOF_ACTUATORS,
)

__all__ = [
    "ADAM_SP_23DOF_ACTUATORS",
    "ADAM_SP_23DOF_BODY_NAMES",
    "ADAM_SP_23DOF_CFG",
    "ADAM_SP_23DOF_COLLISION_BODY_NAMES",
    "ADAM_SP_23DOF_JOINT_NAMES",
    "ADAM_SP_23DOF_JOINT_PROPERTIES",
    "ADAM_SP_23DOF_ROBOT",
    "ADAM_SP_23DOF_URDF",
    "ADAM_SP_23DOF_XML",
    "spawn_adam_sp_23dof",
]
